# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_img.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_img.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rget_img.proto\"A\n\x04img_\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05\x66rame\x18\x03 \x01(\x05\x12\x0b\n\x03img\x18\x04 \x01(\x0c\"\x15\n\x06requst\x12\x0b\n\x03reu\x18\x01 \x01(\t2\'\n\tget_image\x12\x1a\n\x06getimg\x12\x07.requst\x1a\x05.img_\"\x00\x62\x06proto3')
)




_IMG_ = _descriptor.Descriptor(
  name='img_',
  full_name='img_',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='img_.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='img_.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame', full_name='img_.frame', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img', full_name='img_.img', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=82,
)


_REQUST = _descriptor.Descriptor(
  name='requst',
  full_name='requst',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reu', full_name='requst.reu', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['img_'] = _IMG_
DESCRIPTOR.message_types_by_name['requst'] = _REQUST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

img_ = _reflection.GeneratedProtocolMessageType('img_', (_message.Message,), dict(
  DESCRIPTOR = _IMG_,
  __module__ = 'get_img_pb2'
  # @@protoc_insertion_point(class_scope:img_)
  ))
_sym_db.RegisterMessage(img_)

requst = _reflection.GeneratedProtocolMessageType('requst', (_message.Message,), dict(
  DESCRIPTOR = _REQUST,
  __module__ = 'get_img_pb2'
  # @@protoc_insertion_point(class_scope:requst)
  ))
_sym_db.RegisterMessage(requst)



_GET_IMAGE = _descriptor.ServiceDescriptor(
  name='get_image',
  full_name='get_image',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=107,
  serialized_end=146,
  methods=[
  _descriptor.MethodDescriptor(
    name='getimg',
    full_name='get_image.getimg',
    index=0,
    containing_service=None,
    input_type=_REQUST,
    output_type=_IMG_,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GET_IMAGE)

DESCRIPTOR.services_by_name['get_image'] = _GET_IMAGE

# @@protoc_insertion_point(module_scope)
