# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import get_img_pb2 as get__img__pb2


class get_imageStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getimg = channel.unary_unary(
        '/get_image/getimg',
        request_serializer=get__img__pb2.requst.SerializeToString,
        response_deserializer=get__img__pb2.img_.FromString,
        )


class get_imageServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getimg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_get_imageServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getimg': grpc.unary_unary_rpc_method_handler(
          servicer.getimg,
          request_deserializer=get__img__pb2.requst.FromString,
          response_serializer=get__img__pb2.img_.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'get_image', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
